### ISSUE TITLE
Deleting a file that is being watched crashes cordova-simulate

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/cordova-simulate#217]
When a file modification event comes in, cordova-simulate tries to `statSync` it which throws if the file doesn't exist. It'd be much better if we could instead look for the file to be re-created and resume watching then. Currently an ionic build will clean out the www folder and re-create it, which breaks cordova-simulate.

**Comment by tomingoglia** [comment]
This problem manifests itself in VS 2017 when trying to use Ionic 2 with Live Reload. For anyone following this issue and looking for a workaround, there is a option called **forceprepare** that can be used when **livereload** is set to true. If this is set to true, **livereload** will not crash cordova-simulate. 

A simple workaround is to modify the _simulate.js_ file located in the path: _C:\ProgramData\Microsoft\VisualStudio\MDA\975a939a\taco-toolset-6.3.1_

Add the following code to the default configuration attributes in `var = opts {...}`:
`forceprepare: (args["forceprepare"] || "").toLowerCase() !== "false"`

This will default the value to true rather than false if the value is not specified. I'm not sure what effect this will have on other cordova projects, but this fixes the problem with Ionic 2 projects. Based on reading about **forceprepare** and **cordova prepare**, I doubt it will introduce other issues.

Loving VS Code, VS 2017 RC, and the new cordova-simulate features...great work!
