### ISSUE TITLE
Can't use cordova-plugin-file to get a FileEntry object

### ISSUE THREAD

**Issue by cjmackenzie40** [Microsoft/cordova-simulate#258]
When trying to use window.resolveLocalFileSystemURL in cordova simulate (launched from Visual Studio 2017), I get the following error:

> It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources

This may be because one of the Chrome quirks is:

> Chrome requires --allow-file-access-from-files run argument to support API via file:/// protocol

I can't see how to launch Chrome using this switch

There's more information here: https://stackoverflow.com/questions/48100633/how-to-get-fileentry-object-while-using-cordova-simulate

**Comment by ruslan-bikkinin** [comment]
Hi @cjmackenzie40 and sorry for long delay in answering.
Unfortunately, you cannot use `window.resolveLocalFileSystemURL` to get `FileEntry` from `ImageUri` that is returned from `getPicture` method. In original plugin you could specify `DestinationType` to  `Camera.DestinationType.FILE_URI` or `Camera.DestinationType.NATIVE_URI` to get imageUri in needed format but it would be generated on *native side*. In cordova-simulate we have to simulate this by storing files *in browser* using browser File API, that's why we have only two options for making that:
* Return image in base64 format (`DestinationType` is `Camera.DestinationType.DATA_URL`)
* Return blobURL to image (any other `DestinationType` values)

Could you please clarify why do you need exactly FileEntry object? May be image in base64 format will satisfy your needs?

**Comment by cjmackenzie40** [comment]
I didn't want to use base 64 because I was concerned about the size of the
files.
Instead, I simply stopped using Cordova Simulate in my development
environment. Our application is now working and deployed to production.

**Comment by ruslan-bikkinin** [comment]
Thanks for reply, I completely understood your concerns, however if you would have any questions regarding this now or in future - we are all ears. In the meantime I believe we can close the issue, thanks again for your time.
