### ISSUE TITLE
Update cordova-serve to ^2.0.0

### ISSUE THREAD

**Issue by ruslan-bikkinin** [Microsoft/cordova-simulate#269]
Current version (`^1.0.0`) includes several bugs that affects cordova-simulate (#257, #255), so it should be updated to ^2.0.0. This version has breaking changes so we should change our API calls as well and make a proper testing after bumping version.

**Comment by TimBarham** [comment]
I agree we need this change, but there is one thing we need to consider: `cordova-serve` was updated to 2.0.0 because of a breaking API change, and if `cordova-simulate` takes `cordova-serve` `^2.0.0` it will inherit that API change.

The change is that with `cordova-serve` `1.x`, if you don't specify a browser it defaulted to Chrome. With `2.x`, if you don't specify a browser it defaults to your default browser.

IIRC `cordova-simulate` simply passes the browser request through to `cordova-serve`, so `cordova-simulate` will switch from "defaulting to Chrome" to "defaulting to default browser" also. Going forward, that is a good thing, but Visual Studio (and possibly Visual Studio Code - I'm not sure) relies on the current default behavior (that is, Visual Studio uses `cordova-simulate` without specify a browser, and *needs* it to launch Chrome).

So I would like to suggest we pull together all the other fixes that are currently in play and release that as `0.3.15`, then merge this change and release it as `0.4.0`. Any concerns with that suggestion?

**Comment by ruslan-bikkinin** [comment]
Thanks Tim for your feedback. COul you please let me know do we follow semver for cordova-simulate? If we do, we need to release `1.0.0` instead of `0.4.0` I believe.

**Comment by ruslan-bikkinin** [comment]
Got it, @TimBarham, thanks for clarifications.

**Comment by ruslan-bikkinin** [comment]
BTW @TimBarham could you please let me know if you have a plan to release new version of cordova-serve in the near future? If so, what is the target date? I’m asking this because we have issues here #257 and in vscode-cordova https://github.com/Microsoft/vscode-cordova/issues/371 that depends on the fix that has been merged to your master and should be delivered to prod.

**Comment by TimBarham** [comment]
Oh, yeah, we should definitely wait to update `cordova-serve` until there is a release with that fix. I'm not actually actively involved with Cordova anymore, so I won't be doing a release. You could email dev@cordova.apache.org to request a `cordova-serve` release.
