### ISSUE TITLE
Simulate Camera error: Failed to load resource: net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by GregorBiswanger** [Microsoft/cordova-simulate#270]
## Description

The simulate camera feature not working with the default cordova camera plugin code.
I get a Browser Error with: error: Failed to load resource: net::ERR_INVALID_URL

data:image/jpeg;base64,blob:http://localhost:8000/225c5489-a5fe-48e2-a878-131484208f95

## Steps to Reproduce

```js
        document.getElementById("cameraButton").addEventListener("click", () => {
            navigator.camera.getPicture(cameraSuccess);
        });

        function cameraSuccess(imageData) {
            var image = document.getElementById('myImage');
            image.src = "data:image/jpeg;base64," + imageData;
        }
```

## Software versions
- `cordova-simulate` version: 
- OS platform and version: Windows 10
- Cordova version: 8.0
- Cordova-Android/iOS/Windows version: Browser
- List of installed plugins:

**Comment by ruslan-bikkinin** [comment]
Hi @GregorBiswanger and thanks for reaching us. I can reproduce it on out side, so I'll keep you posted about the status of this bug.

**Comment by ruslan-bikkinin** [comment]
Hi @GregorBiswanger 
I investigated this and found out that it is not a bug, but misconfiguration. As I understand, you are trying to insert image into `<img>` element in your document. To do that you need to pass {destinationType: 0} as third parameter to `getPicture` method, so then the result will be base64 encoded string instead of url. Please check out the [official documentation](https://github.com/apache/cordova-plugin-camera#module_Camera.DestinationType) for cordova-plugin-camera plugin for more info.

So you need to change your code to something like this:
```js
        document.getElementById("cameraButton").addEventListener("click", () => {
            navigator.camera.getPicture(cameraSuccess, cameraFail, { destinationType: 0 });
        });

        function cameraSuccess(imageData) {
            var image = document.getElementById('myImage');
            image.src = "data:image/jpeg;base64," + imageData;
        }

        function cameraFail(error) {
            console.error(error);
        }
```

Please let us know if it helps or you have any other questions regarding this.

**Comment by GregorBiswanger** [comment]
Thank you for your support! :)
