### ISSUE TITLE
Cant debug with cordova-simulate from VSCode

### ISSUE THREAD

**Issue by rido-min** [Microsoft/cordova-simulate#35]
Creating a default Ionic2 app (now in Beta7) I can debug in browser and device, however if I run cordova-simulate I can not hit BreakPoints from VSCode

**Comment by axemclion** [comment]
@rido-min More details would help. In this video, I am able to hit the breakpoints - https://www.youtube.com/watch?v=LdFT6xxhSbw

Is this an issue caused due to the project? Is this an issue with sourcemaps - if yes, this could be an issue with - http://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code ? 

Are you able to use the chrome debugger and attach to it ?

**Comment by dlebu** [comment]
@rido-min This seems like a VSCode issue and not a simulate issue. Can you move it to https://github.com/Microsoft/vscode-cordova ? 

Are you debugging typescript or js? We know that TS debugging for Ionic 2 does not work in our extension.

**Comment by rido-min** [comment]
I think this is the same issue https://github.com/Microsoft/vscode-cordova/issues/92  

Do you know why Ionic 2 debugging is not working?
